// @generated - This file is auto-generated by doc-toc. Do not edit manually.

// Auto-generated by doctoc - DO NOT EDIT
// This file is automatically generated. Any manual changes will be overwritten.

import type { DefaultTheme } from 'vitepress';

export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "一、环境与基础",
    "items": [
      {
        "text": "1.1 工程架构搭建",
        "link": "/docs/一、环境与基础/1.1 工程架构搭建"
      },
      {
        "text": "1.2 模块初始化",
        "link": "/docs/一、环境与基础/1.2 模块初始化"
      }
    ],
    "collapsed": false
  },
  {
    "text": "二、响应式系统",
    "items": [
      {
        "text": "2.1 Reactivity 核心",
        "items": [
          {
            "text": "2.1.1 reactivity 的核心流程",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.1 Reactivity 核心"
          },
          {
            "text": "2.1.2 Reactivity的基础实现",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.2 Reactivity的基础实现"
          },
          {
            "text": "2.1.3 实现 effect 函数返回 runner",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.3 实现 effect 函数返回 runner"
          },
          {
            "text": "2.1.4 实现 effect 的 stop 功能 & 优化 stop 功能",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.4 实现 effect 的 stop 功能 & 优化 stop 功能"
          },
          {
            "text": "2.1.5 effect防止死循环（无限递归）",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.5 effect防止死循环（无限递归）"
          },
          {
            "text": "2.1.6 实现 effect 的 scheduler 功能",
            "link": "/docs/二、响应式系统/2.1 Reactivity 核心/2.1.6 实现 effect 的 scheduler 功能"
          }
        ],
        "collapsed": false
      },
      {
        "text": "2.2 扩展响应式对象",
        "items": [
          {
            "text": "2.2.1 工程化重构",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.1 工程化重构"
          },
          {
            "text": "2.2.2 实现 readonly 功能",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.2 实现 readonly 功能"
          },
          {
            "text": "2.2.3 实现 isReactive 和 isReadonly和isProxy",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.3 实现 isReactive 和 isReadonly和isProxy"
          },
          {
            "text": "2.2.4 实现 reactive 和 readonly 嵌套对象转换功能 - 深层代理",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.4 深层代理"
          },
          {
            "text": "2.2.5 实现 shallow功能（浅响应式）",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.5 深层代理下的单例缓存机制"
          },
          {
            "text": "2.2.6 实现 shallow功能（浅响应式）",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.6 实现 shallow功能（浅响应式）"
          },
          {
            "text": "2.2.7 实现 toRaw",
            "link": "/docs/二、响应式系统/2.2 扩展响应式对象/2.2.7 实现 toRaw"
          }
        ],
        "collapsed": false
      },
      {
        "text": "2.3 Ref 系统",
        "items": [
          {
            "text": "2.3.1 实现 ref 功能",
            "link": "/docs/二、响应式系统/2.3 Ref 系统/2.3.1 实现 ref 功能"
          },
          {
            "text": "2.3.2 实现 isRef 和 unRef 功能",
            "link": "/docs/二、响应式系统/2.3 Ref 系统/2.3.2 实现 isRef 和 unRef 功能"
          },
          {
            "text": "2.3.3 实现 proxyR",
            "link": "/docs/二、响应式系统/2.3 Ref 系统/2.3.3 实现 proxyR"
          },
          {
            "text": "2.3.4 实现 toRef & toRefs",
            "link": "/docs/二、响应式系统/2.3 Ref 系统/2.3.4 实现 toRef & toRefs"
          }
        ],
        "collapsed": false
      },
      {
        "text": "2.4 Computed",
        "items": [
          {
            "text": "2.4.1 基础实现",
            "link": "/docs/二、响应式系统/2.4 Computed/2.4.1 基础实现"
          },
          {
            "text": "2.4.2 Computed 矛盾的选择",
            "link": "/docs/二、响应式系统/2.4 Computed/2.4.2 Computed 矛盾的选择"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "三、运行时",
    "items": [
      {
        "text": "3.1 概述",
        "items": [
          {
            "text": "3.1.1 运行时概述",
            "link": "/docs/三、运行时/3.1 概述/3.1 运行时概述【重要】"
          }
        ],
        "collapsed": false
      },
      {
        "text": "3.2 初始化流程",
        "items": [
          {
            "text": "3.2.1 runtime-core 流程概览 & `createApp` 入口",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.1 runtime-core 流程概览 & createApp 入口"
          },
          {
            "text": "3.2.2 实现createVNode（很重要）",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.2 实现 createRenderer"
          },
          {
            "text": "3.2.3 实现 `createRenderer` (渲染器工厂函数)",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.3 实现 createRenderer (渲染器工厂函数) "
          },
          {
            "text": "3.2.4 完善 VNode (ShapeFlags)",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.4 完善 VNode (ShapeFlags)"
          },
          {
            "text": "3.2.5 实现初始化 component 主流程",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.5 实现初始化 component 主流程"
          },
          {
            "text": "3.2.6 实现初始化 element 主流程",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.6 实现初始化 element 主流程"
          },
          {
            "text": "3.2.7 基础实现 runtime-dom",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.7 基础实现 runtime-dom"
          },
          {
            "text": "3.2.8 注册事件功能 (处理 @click)",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.8 注册事件功能 (处理 @click)"
          },
          {
            "text": "3.2.10 实现自定义渲染器 custom renderer",
            "link": "/docs/三、运行时/3.2 初始化流程/3.2.9 实现自定义渲染器 custom renderer"
          }
        ],
        "collapsed": false
      },
      {
        "text": "3.3 组件实例与功能",
        "items": [
          {
            "text": "3.3.1 实现组件代理",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.1 实现组件代理"
          },
          {
            "text": "3.3.2 实现组件 props 功能",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.2 实现组件 props 功能"
          },
          {
            "text": "3.3.3 实现组件 emit 功能",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.3 实现组件 emit 功能"
          },
          {
            "text": "3.3.4 实现组件 slots 功能",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.4 实现组件 slots 功能"
          },
          {
            "text": "3.3.5 实现 getCurrentInstance",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.5 实现 getCurrentInstance"
          },
          {
            "text": "3.3.6 实现依赖注入功能 provide/inject",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.6 实现依赖注入功能inject & provide"
          },
          {
            "text": "3.3.7 实现 Lifecycle Hooks",
            "link": "/docs/三、运行时/3.3 组件实例与功能/3.3.7 实现 Lifecycle Hooks"
          }
        ],
        "collapsed": false
      },
      {
        "text": "3.4 更新流程",
        "items": [
          {
            "text": "3.4.1 runtime-core 更新的核心流程",
            "link": "/docs/三、运行时/3.4 更新流程/3.4.1 runtime-core 更新的核心流程"
          },
          {
            "text": "3.4.2 重构setupRenderEffect",
            "link": "/docs/三、运行时/3.4 更新流程/3.4.2 重构setupRenderEffect"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "index",
    "link": "/docs/index"
  }
];
